# Air configuration file
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/app"
bin = "tmp/main"
full_bin = "sh -c 'tmp/main'"

[watcher]
use_polling = true
extensions = ["go"]
exclude_dirs = ["tmp", "vendor"]